from __future__ import annotations

import argparse
import copy
import contextlib
import io
import json
import os
import shlex
from pathlib import Path
from typing import Any

from hybrid_sensor_sim.tools.renderer_backend_local_setup import (
    _render_env_file as _render_local_setup_env_file,
)
from hybrid_sensor_sim.tools.renderer_backend_local_setup import (
    _inspect_executable_host_compatibility,
)
from hybrid_sensor_sim.tools.renderer_backend_local_setup import (
    build_renderer_backend_local_setup,
)
from hybrid_sensor_sim.tools.renderer_backend_package_acquire import (
    build_renderer_backend_package_acquire,
)
from hybrid_sensor_sim.tools.renderer_backend_smoke import (
    _build_effective_config as _build_smoke_effective_config,
)
from hybrid_sensor_sim.tools.renderer_backend_smoke import main as smoke_main


_DEFAULT_SMOKE_PRESETS = {
    "awsim": {
        "binary": "configs/renderer_backend_smoke.awsim.local.example.json",
        "docker": "configs/renderer_backend_smoke.awsim.local.docker.example.json",
    },
    "carla": {
        "binary": "configs/renderer_backend_smoke.carla.local.example.json",
        "docker": "configs/renderer_backend_smoke.carla.local.docker.example.json",
    },
}
_BACKEND_ENV_VARS = {
    "awsim": ("AWSIM_BIN", "AWSIM_RENDERER_MAP"),
    "carla": ("CARLA_BIN", "CARLA_RENDERER_MAP"),
}


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run local backend discovery/acquire/smoke as a single workflow."
    )
    parser.add_argument(
        "--backend",
        choices=("awsim", "carla"),
        required=True,
        help="Backend workflow to execute.",
    )
    parser.add_argument(
        "--setup-summary",
        type=Path,
        help="Existing renderer_backend_local_setup.json. If omitted, discovery is run automatically.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        help="Optional smoke base config. If omitted, the backend local preset is selected automatically.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        help="Directory for workflow artifacts. Defaults to artifacts/renderer_backend_workflow/<backend>.",
    )
    parser.add_argument(
        "--backend-bin",
        help="Explicit backend runtime path override.",
    )
    parser.add_argument(
        "--renderer-map",
        help="Explicit renderer map/town override.",
    )
    parser.add_argument(
        "--auto-acquire",
        action="store_true",
        help="If the backend runtime is missing, try package acquire+stage automatically before smoke.",
    )
    parser.add_argument(
        "--download-url",
        help="Explicit package URL passed through to acquire when --auto-acquire is enabled.",
    )
    parser.add_argument(
        "--download-name",
        help="Explicit local archive filename passed through to acquire.",
    )
    parser.add_argument(
        "--download-dir",
        type=Path,
        help="Download target directory for acquire. Defaults to ~/Downloads.",
    )
    parser.add_argument(
        "--overwrite-download",
        action="store_true",
        help="Force re-download during acquire.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Resolve setup/acquire/smoke decisions without executing smoke.",
    )
    parser.add_argument(
        "--set-option",
        action="append",
        default=[],
        help="Forwarded to renderer_backend_smoke.py when smoke runs.",
    )
    return parser.parse_args(argv)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _write_text(path: Path, payload: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")


def _write_executable_text(path: Path, payload: str) -> None:
    _write_text(path, payload)
    path.chmod(path.stat().st_mode | 0o111)


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"JSON payload at {path} must be an object.")
    return payload


def _resolve_path(raw: str | Path) -> Path:
    path = Path(raw).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (Path.cwd() / path).resolve()


def _selection_value(selection: dict[str, Any], key: str) -> str | None:
    value = selection.get(key)
    if value is None:
        return None
    text = str(value).strip()
    return text if text else None


def _render_workflow_env_file(summary: dict[str, Any]) -> str:
    selection = summary.get("final_selection", {})
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by renderer_backend_workflow.py",
        "# Source this file to reuse the latest workflow selections.",
        "",
    ]
    for env_key in (
        "HELIOS_BIN",
        "HELIOS_DOCKER_IMAGE",
        "HELIOS_DOCKER_BINARY",
        "AWSIM_BIN",
        "AWSIM_RENDERER_MAP",
        "CARLA_BIN",
        "CARLA_RENDERER_MAP",
    ):
        value = selection.get(env_key) if isinstance(selection, dict) else None
        if value:
            lines.append(f"export {env_key}={shlex.quote(str(value))}")
        else:
            lines.append(f"# export {env_key}=<set-me>")
    lines.extend(
        [
            "",
            f"# backend={summary.get('backend')}",
            f"# status={summary.get('status')}",
            f"# success={summary.get('success')}",
        ]
    )
    recommended = summary.get("recommended_next_command")
    if recommended:
        lines.append(f"# next: {recommended}")
    commands = summary.get("commands", {})
    if isinstance(commands, dict):
        smoke_command = commands.get("smoke")
        acquire_command = commands.get("acquire")
        if smoke_command:
            lines.append(f"# smoke: {smoke_command}")
        if acquire_command:
            lines.append(f"# acquire: {acquire_command}")
    lines.append("")
    return "\n".join(lines)


def _render_workflow_markdown_report(summary: dict[str, Any], summary_path: Path) -> str:
    def _inline(value: Any) -> str:
        if value is None:
            return "-"
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value).replace("\n", " ").strip() or "-"

    lines = [
        "# Renderer Backend Workflow Report",
        "",
        "## Overview",
        f"- backend: `{_inline(summary.get('backend'))}`",
        f"- status: `{_inline(summary.get('status'))}`",
        f"- success: `{_inline(summary.get('success'))}`",
        f"- dry run: `{_inline(summary.get('dry_run'))}`",
        f"- summary json: `{summary_path}`",
        "",
    ]
    recommended = summary.get("recommended_next_command")
    if recommended:
        lines.extend(
            [
                "## Next Command",
                f"- `{recommended}`",
                "",
            ]
        )
    issues = summary.get("issues", [])
    if isinstance(issues, list) and issues:
        lines.append("## Issues")
        for issue in issues:
            lines.append(f"- `{_inline(issue)}`")
        lines.append("")
    blockers = summary.get("blockers", [])
    if isinstance(blockers, list) and blockers:
        lines.extend(
            [
                "## Blockers",
                "| Code | Severity | Message | Recommended Command |",
                "| --- | --- | --- | --- |",
            ]
        )
        for blocker in blockers:
            if not isinstance(blocker, dict):
                continue
            lines.append(
                "| {code} | {severity} | `{message}` | `{recommended}` |".format(
                    code=_inline(blocker.get("code")),
                    severity=_inline(blocker.get("severity")),
                    message=_inline(blocker.get("message")),
                    recommended=_inline(blocker.get("recommended_command")),
                )
            )
        lines.append("")
    final_selection = summary.get("final_selection", {})
    if isinstance(final_selection, dict) and final_selection:
        lines.extend(
            [
                "## Final Selection",
                "| Key | Value |",
                "| --- | --- |",
            ]
        )
        for key in sorted(final_selection):
            lines.append(f"| {key} | `{_inline(final_selection[key])}` |")
        lines.append("")
    smoke = summary.get("smoke", {})
    if isinstance(smoke, dict):
        lines.extend(
            [
                "## Smoke",
                f"- ready: `{_inline(smoke.get('ready'))}`",
                f"- executed: `{_inline(smoke.get('executed'))}`",
                f"- exit_code: `{_inline(smoke.get('exit_code'))}`",
                f"- config: `{_inline(smoke.get('config_path'))}`",
                "",
            ]
        )
    linux_handoff = summary.get("linux_handoff", {})
    if isinstance(linux_handoff, dict) and linux_handoff:
        lines.extend(
            [
                "## Linux Runner Handoff",
                f"- ready: `{_inline(linux_handoff.get('ready'))}`",
                f"- target platform: `{_inline(linux_handoff.get('target_platform'))}`",
                f"- command: `{_inline(linux_handoff.get('runner_command'))}`",
                f"- script command: `{_inline(linux_handoff.get('script_command'))}`",
                "",
            ]
        )
        required_env_vars = linux_handoff.get("required_env_vars", [])
        if isinstance(required_env_vars, list) and required_env_vars:
            lines.append("### Required Env")
            for item in required_env_vars:
                lines.append(f"- `{_inline(item)}`")
            lines.append("")
        transfer_candidates = linux_handoff.get("transfer_candidates", [])
        if isinstance(transfer_candidates, list) and transfer_candidates:
            lines.extend(
                [
                    "### Transfer Candidates",
                    "| Type | Env Var | Local Path |",
                    "| --- | --- | --- |",
                ]
            )
            for item in transfer_candidates:
                if not isinstance(item, dict):
                    continue
                lines.append(
                    "| {kind} | {env_var} | `{path}` |".format(
                        kind=_inline(item.get("kind")),
                        env_var=_inline(item.get("env_var")),
                        path=_inline(item.get("local_path")),
                    )
                )
            lines.append("")
    commands = summary.get("commands", {})
    if isinstance(commands, dict) and commands:
        lines.extend(
            [
                "## Commands",
                "| Command | Value |",
                "| --- | --- |",
            ]
        )
        for key in sorted(commands):
            lines.append(f"| {key} | `{_inline(commands[key])}` |")
        lines.append("")
    return "\n".join(lines)


def _build_or_load_setup_summary(
    *,
    repo_root: Path,
    workflow_root: Path,
    setup_summary_path: Path | None,
) -> tuple[dict[str, Any], Path, bool]:
    if setup_summary_path is not None:
        resolved = _resolve_path(setup_summary_path)
        return _load_json(resolved), resolved, False

    local_setup_root = workflow_root / "local_setup"
    summary = build_renderer_backend_local_setup(
        repo_root=repo_root,
        output_dir=local_setup_root,
    )
    summary_path = Path(summary["artifacts"]["summary_path"])
    env_path = Path(summary["artifacts"]["env_path"])
    _write_json(summary_path, summary)
    _write_text(env_path, _render_local_setup_env_file(summary))
    return summary, summary_path, True


def _reuse_search_roots_from_setup(summary: dict[str, Any]) -> list[Path]:
    raw_search_roots = summary.get("search_roots", [])
    if not isinstance(raw_search_roots, list):
        return []
    roots: list[Path] = []
    seen: set[str] = set()
    for item in raw_search_roots:
        if not isinstance(item, str) or not item.strip():
            continue
        path = _resolve_path(item)
        key = str(path)
        if key in seen:
            continue
        seen.add(key)
        roots.append(path)
    return roots


def _refresh_setup_summary(
    *,
    repo_root: Path,
    workflow_root: Path,
    prior_summary: dict[str, Any],
) -> tuple[dict[str, Any], Path, Path]:
    refresh_root = workflow_root / "local_setup_refreshed"
    refreshed = build_renderer_backend_local_setup(
        repo_root=repo_root,
        search_roots=_reuse_search_roots_from_setup(prior_summary),
        output_dir=refresh_root,
        include_default_search_roots=False,
    )
    summary_path = Path(refreshed["artifacts"]["summary_path"])
    env_path = Path(refreshed["artifacts"]["env_path"])
    _write_json(summary_path, refreshed)
    _write_text(env_path, _render_local_setup_env_file(refreshed))
    return refreshed, summary_path, env_path


def _build_blockers(
    *,
    backend: str,
    setup_summary: dict[str, Any],
    helios_ready: bool,
    backend_bin: str | None,
    backend_host_compatible: bool,
    backend_host_compatibility_reason: str | None,
    auto_acquire: bool,
    acquire_summary: dict[str, Any] | None,
    smoke_executed: bool,
    smoke_exit_code: int | None,
    planned_smoke_config_ready: bool,
    planned_smoke_config_error: str | None,
    recommended_next_command: str | None,
) -> list[dict[str, Any]]:
    blockers: list[dict[str, Any]] = []
    acquisition_hints = setup_summary.get("acquisition_hints", {})
    backend_hints = acquisition_hints.get(backend, {}) if isinstance(acquisition_hints, dict) else {}
    if isinstance(backend_hints, dict) and backend_hints.get("platform_supported") is False:
        blockers.append(
            {
                "code": "BACKEND_PLATFORM_UNSUPPORTED",
                "severity": "warning",
                "message": str(backend_hints.get("platform_note") or f"{backend} platform unsupported"),
                "recommended_command": recommended_next_command,
            }
        )
    if not helios_ready:
        blockers.append(
            {
                "code": "HELIOS_RUNTIME_MISSING",
                "severity": "blocking",
                "message": "HELIOS runtime is not ready for backend smoke.",
                "recommended_command": None,
            }
        )
    if backend_bin is None:
        blockers.append(
            {
                "code": "BACKEND_BIN_MISSING",
                "severity": "blocking",
                "message": f"{backend.upper()} runtime binary is not resolved.",
                "recommended_command": recommended_next_command,
            }
        )
        if not auto_acquire:
            blockers.append(
                {
                    "code": "AUTO_ACQUIRE_DISABLED",
                    "severity": "blocking",
                    "message": "Workflow did not attempt package acquire because --auto-acquire is disabled.",
                    "recommended_command": recommended_next_command,
                }
            )
    elif not backend_host_compatible:
        blockers.append(
            {
                "code": "BACKEND_HOST_INCOMPATIBLE",
                "severity": "blocking",
                "message": (
                    backend_host_compatibility_reason
                    or f"{backend.upper()} runtime binary is not executable on the current host."
                ),
                "recommended_command": None,
            }
        )
    if auto_acquire and isinstance(acquire_summary, dict):
        acquire_readiness = acquire_summary.get("readiness", {})
        if acquire_readiness.get("download_url_resolved") is False:
            blockers.append(
                {
                    "code": "ACQUIRE_SOURCE_UNRESOLVED",
                    "severity": "blocking",
                    "message": "No package URL or local archive candidate was resolved for auto-acquire.",
                    "recommended_command": recommended_next_command,
                }
            )
        elif acquire_readiness.get("stage_ready") is False and backend_bin is None:
            blockers.append(
                {
                    "code": "ACQUIRE_OR_STAGE_FAILED",
                    "severity": "blocking",
                    "message": "Package acquire completed without producing a runnable backend binary.",
                    "recommended_command": recommended_next_command,
                }
            )
    if not planned_smoke_config_ready and planned_smoke_config_error:
        blockers.append(
            {
                "code": "SMOKE_CONFIG_UNRESOLVED",
                "severity": "blocking",
                "message": planned_smoke_config_error,
                "recommended_command": recommended_next_command,
            }
        )
    if smoke_executed and smoke_exit_code not in (None, 0):
        blockers.append(
            {
                "code": "SMOKE_EXECUTION_FAILED",
                "severity": "blocking",
                "message": f"Backend smoke exited with code {smoke_exit_code}.",
                "recommended_command": recommended_next_command,
            }
        )
    return blockers


def _relative_to_root(path: Path, root: Path) -> str | None:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return None


def _prepare_linux_runner_path_binding(
    *,
    raw_path: str | None,
    repo_root: Path,
    env_var: str,
    kind: str,
) -> tuple[str | None, dict[str, Any] | None]:
    if raw_path is None:
        return None, None
    resolved = _resolve_path(raw_path)
    relative = _relative_to_root(resolved, repo_root)
    binding = {
        "kind": kind,
        "env_var": env_var,
        "local_path": str(resolved),
        "repo_relative_path": relative,
        "uses_env": relative is None,
    }
    if relative is not None:
        return relative, binding
    return f"${{{env_var}}}", binding


def _render_linux_handoff_env_file(handoff: dict[str, Any]) -> str:
    backend = handoff.get("backend")
    bindings = handoff.get("path_bindings", {})
    selection = handoff.get("selection", {})
    linux_paths = handoff.get("linux_paths", {})
    required_env_vars = set(handoff.get("required_env_vars", []))
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by renderer_backend_workflow.py",
        "# Source this file on a Linux runner before executing the handoff script.",
        "",
    ]
    config_path = linux_paths.get("handoff_config_path")
    if config_path:
        lines.append(
            f'export HANDOFF_SMOKE_CONFIG_PATH="${{HANDOFF_SMOKE_CONFIG_PATH:-{config_path}}}"'
        )
    else:
        lines.append("# export HANDOFF_SMOKE_CONFIG_PATH=<linux-path-to-renderer_backend_workflow_linux_handoff_config.json>")
    lines.append('export WORKFLOW_REPO_ROOT="${WORKFLOW_REPO_ROOT:-$(pwd)}"')
    backend_env_var, map_env_var = _BACKEND_ENV_VARS[str(backend)]
    backend_binding = bindings.get("backend_bin", {}) if isinstance(bindings, dict) else {}
    backend_relative = backend_binding.get("repo_relative_path") if isinstance(backend_binding, dict) else None
    if backend_relative:
        lines.append(f'export {backend_env_var}="${{{backend_env_var}:-{backend_relative}}}"')
    else:
        lines.append(f"# export {backend_env_var}=<linux-path-to-{backend}-runtime>")
    map_value = selection.get(map_env_var) if isinstance(selection, dict) else None
    if map_value:
        lines.append(f"export {map_env_var}={shlex.quote(str(map_value))}")
    else:
        lines.append(f"# export {map_env_var}=<set-me>")
    scenario_binding = bindings.get("scenario_path", {}) if isinstance(bindings, dict) else {}
    scenario_relative = scenario_binding.get("repo_relative_path") if isinstance(scenario_binding, dict) else None
    if scenario_relative:
        lines.append(f'export HANDOFF_SCENARIO_PATH="${{HANDOFF_SCENARIO_PATH:-{scenario_relative}}}"')
    elif "HANDOFF_SCENARIO_PATH" in required_env_vars:
        lines.append("# export HANDOFF_SCENARIO_PATH=<linux-path-to-scenario>")
    helios_binding = bindings.get("helios_bin", {}) if isinstance(bindings, dict) else {}
    helios_relative = helios_binding.get("repo_relative_path") if isinstance(helios_binding, dict) else None
    if helios_relative:
        lines.append(f'export HELIOS_BIN="${{HELIOS_BIN:-{helios_relative}}}"')
    elif "HELIOS_BIN" in required_env_vars:
        lines.append("# export HELIOS_BIN=<linux-path-to-helios-binary>")
    helios_docker_image = selection.get("HELIOS_DOCKER_IMAGE") if isinstance(selection, dict) else None
    helios_docker_binary = selection.get("HELIOS_DOCKER_BINARY") if isinstance(selection, dict) else None
    if helios_docker_image:
        lines.append(f"export HELIOS_DOCKER_IMAGE={shlex.quote(str(helios_docker_image))}")
    if helios_docker_binary:
        lines.append(f"export HELIOS_DOCKER_BINARY={shlex.quote(str(helios_docker_binary))}")
    lines.append("")
    return "\n".join(lines)


def _render_linux_handoff_script(handoff: dict[str, Any]) -> str:
    env_path = handoff.get("linux_paths", {}).get("handoff_env_path")
    backend = handoff.get("backend")
    runner_command = handoff.get("runner_command")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by renderer_backend_workflow.py",
        "",
    ]
    if env_path:
        lines.append(f"source {shlex.quote(str(env_path))}")
    else:
        lines.append("# export HANDOFF_SMOKE_CONFIG_PATH before running this script")
    lines.extend(
        [
            'REPO_ROOT="${WORKFLOW_REPO_ROOT:-$(pwd)}"',
            'CONFIG_PATH="${HANDOFF_SMOKE_CONFIG_PATH:?set HANDOFF_SMOKE_CONFIG_PATH}"',
            f'python3 "$REPO_ROOT/scripts/run_renderer_backend_smoke.py" --config "$CONFIG_PATH" --backend {backend}',
            "",
        ]
    )
    if runner_command:
        lines.append(f"# equivalent: {runner_command}")
        lines.append("")
    return "\n".join(lines)


def _build_linux_handoff(
    *,
    backend: str,
    repo_root: Path,
    workflow_root: Path,
    final_selection: dict[str, Any],
    planned_effective_config: dict[str, Any],
    planned_smoke_config_ready: bool,
    planned_smoke_config_error: str | None,
    selected_backend_bin: str | None,
    selected_renderer_map: str | None,
    backend_host_compatible: bool,
    backend_host_compatibility_reason: str | None,
    acquire_summary: dict[str, Any] | None,
) -> dict[str, Any]:
    backend_env_var, map_env_var = _BACKEND_ENV_VARS[backend]
    workflow_relative = _relative_to_root(workflow_root, repo_root)
    linux_workflow_dir = workflow_relative or f"artifacts/renderer_backend_workflow/{backend}"
    handoff_config_path = workflow_root / "renderer_backend_workflow_linux_handoff_config.json"
    handoff_env_path = workflow_root / "renderer_backend_workflow_linux_handoff.env.sh"
    handoff_script_path = workflow_root / "renderer_backend_workflow_linux_handoff.sh"
    handoff_script_relative = _relative_to_root(handoff_script_path, repo_root)
    ready = bool(planned_smoke_config_ready)
    path_bindings: dict[str, Any] = {}
    required_env_vars: list[str] = []
    transfer_candidates: list[dict[str, Any]] = []
    handoff_config = (
        copy.deepcopy(planned_effective_config)
        if planned_smoke_config_ready
        else {
            "error": planned_smoke_config_error or "Planned smoke config is not ready.",
        }
    )

    if planned_smoke_config_ready:
        scenario_value, scenario_binding = _prepare_linux_runner_path_binding(
            raw_path=str(handoff_config.get("scenario_path")) if handoff_config.get("scenario_path") else None,
            repo_root=repo_root,
            env_var="HANDOFF_SCENARIO_PATH",
            kind="scenario",
        )
        if scenario_value is not None:
            handoff_config["scenario_path"] = scenario_value
        if scenario_binding is not None:
            path_bindings["scenario_path"] = scenario_binding
            if scenario_binding["uses_env"]:
                required_env_vars.append("HANDOFF_SCENARIO_PATH")
                transfer_candidates.append(scenario_binding)

        if handoff_config.get("helios_bin"):
            helios_value, helios_binding = _prepare_linux_runner_path_binding(
                raw_path=str(handoff_config.get("helios_bin")),
                repo_root=repo_root,
                env_var="HELIOS_BIN",
                kind="helios_binary",
            )
            if helios_value is not None:
                handoff_config["helios_bin"] = helios_value
            if helios_binding is not None:
                path_bindings["helios_bin"] = helios_binding
                if helios_binding["uses_env"]:
                    required_env_vars.append("HELIOS_BIN")
                    transfer_candidates.append(helios_binding)

        handoff_config["output_dir"] = f"{linux_workflow_dir}/linux_handoff/smoke_run"
        options = dict(handoff_config.get("options", {}))
        for key in ("renderer_cwd", "renderer_bin", "awsim_wrapper", "carla_wrapper"):
            options.pop(key, None)
        backend_value, backend_binding = _prepare_linux_runner_path_binding(
            raw_path=selected_backend_bin,
            repo_root=repo_root,
            env_var=backend_env_var,
            kind="backend_runtime",
        )
        if backend_value is not None:
            options[f"{backend}_bin"] = backend_value
        if backend_binding is not None:
            path_bindings["backend_bin"] = backend_binding
            if backend_binding["uses_env"]:
                required_env_vars.append(backend_env_var)
                transfer_candidates.append(backend_binding)
        if selected_renderer_map is not None:
            options["renderer_map"] = selected_renderer_map
        handoff_config["options"] = options

    acquire_download = acquire_summary.get("download", {}) if isinstance(acquire_summary, dict) else {}
    if isinstance(acquire_download, dict):
        archive_path = acquire_download.get("target_path")
        if isinstance(archive_path, str) and archive_path.strip():
            transfer_candidates.append(
                {
                    "kind": "backend_archive",
                    "env_var": None,
                    "local_path": str(_resolve_path(archive_path)),
                    "repo_relative_path": _relative_to_root(_resolve_path(archive_path), repo_root),
                    "uses_env": False,
                }
            )

    reason_codes: list[str] = []
    if selected_backend_bin is not None and not backend_host_compatible:
        reason_codes.append("BACKEND_HOST_INCOMPATIBLE")
    if backend_host_compatibility_reason:
        reason_codes.append("HOST_COMPATIBILITY_REASON_AVAILABLE")
    runner_command = (
        f'python3 scripts/run_renderer_backend_smoke.py --config "${{HANDOFF_SMOKE_CONFIG_PATH}}" --backend {backend}'
    )
    script_command = (
        f"bash {handoff_script_relative}"
        if handoff_script_relative is not None
        else f"bash {handoff_script_path.name}"
    )
    return {
        "ready": ready,
        "backend": backend,
        "target_platform": "Linux x86_64",
        "reason_codes": reason_codes,
        "reason": backend_host_compatibility_reason,
        "required_env_vars": sorted(set(required_env_vars)),
        "path_bindings": path_bindings,
        "transfer_candidates": transfer_candidates,
        "selection": final_selection,
        "config": handoff_config,
        "runner_command": runner_command,
        "script_command": script_command,
        "linux_paths": {
            "workflow_dir": linux_workflow_dir,
            "handoff_config_path": (
                f"{linux_workflow_dir}/renderer_backend_workflow_linux_handoff_config.json"
            ),
            "handoff_env_path": (
                f"{linux_workflow_dir}/renderer_backend_workflow_linux_handoff.env.sh"
            ),
            "handoff_script_path": (
                f"{linux_workflow_dir}/renderer_backend_workflow_linux_handoff.sh"
            ),
        },
        "artifacts": {
            "handoff_config_path": str(handoff_config_path),
            "handoff_env_path": str(handoff_env_path),
            "handoff_script_path": str(handoff_script_path),
        },
    }


def _render_next_step_script(summary: dict[str, Any]) -> str:
    env_path = summary.get("artifacts", {}).get("env_path")
    recommended = summary.get("recommended_next_command")
    rerun_smoke_command = summary.get("commands", {}).get("rerun_smoke")
    smoke_command = summary.get("commands", {}).get("smoke")
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by renderer_backend_workflow.py",
        "",
    ]
    if env_path:
        lines.append(f"source {shlex.quote(str(env_path))}")
    lines.append("")
    if recommended:
        lines.append(recommended)
    elif rerun_smoke_command:
        lines.append(rerun_smoke_command)
    elif smoke_command:
        lines.append(smoke_command)
    else:
        lines.append("echo 'No recommended next command available.'")
        lines.append("exit 1")
    lines.append("")
    return "\n".join(lines)


def _determine_smoke_config(
    *,
    backend: str,
    repo_root: Path,
    explicit_config: Path | None,
    selection: dict[str, Any],
) -> tuple[Path, str]:
    if explicit_config is not None:
        return _resolve_path(explicit_config), "explicit"
    helios_bin = _selection_value(selection, "HELIOS_BIN")
    use_docker = not helios_bin and bool(
        _selection_value(selection, "HELIOS_DOCKER_IMAGE")
        and _selection_value(selection, "HELIOS_DOCKER_BINARY")
    )
    mode = "docker" if use_docker else "binary"
    return (repo_root / _DEFAULT_SMOKE_PRESETS[backend][mode]).resolve(), f"default_{mode}_preset"


def build_renderer_backend_workflow(
    *,
    backend: str,
    repo_root: Path,
    workflow_root: Path,
    setup_summary_path: Path | None = None,
    config_path: Path | None = None,
    backend_bin_override: str | None = None,
    renderer_map_override: str | None = None,
    auto_acquire: bool = False,
    download_url: str | None = None,
    download_name: str | None = None,
    download_dir: Path | None = None,
    overwrite_download: bool = False,
    dry_run: bool = False,
    option_overrides: list[str] | None = None,
) -> dict[str, Any]:
    backend = backend.strip().lower()
    if backend not in _BACKEND_ENV_VARS:
        raise ValueError(f"Unsupported backend: {backend}")
    repo_root = repo_root.resolve()
    workflow_root = workflow_root.resolve()
    workflow_root.mkdir(parents=True, exist_ok=True)
    issues: list[str] = []
    option_overrides = list(option_overrides or [])

    setup_summary, resolved_setup_summary_path, generated_setup = _build_or_load_setup_summary(
        repo_root=repo_root,
        workflow_root=workflow_root,
        setup_summary_path=setup_summary_path,
    )
    setup_readiness = setup_summary.get("readiness", {})
    setup_selection = dict(setup_summary.get("selection", {}))
    backend_env_var, map_env_var = _BACKEND_ENV_VARS[backend]

    acquire_summary: dict[str, Any] | None = None
    refreshed_setup_summary: dict[str, Any] | None = None
    refreshed_setup_summary_path: Path | None = None
    refreshed_setup_env_path: Path | None = None
    selected_backend_bin = (
        str(_resolve_path(backend_bin_override))
        if backend_bin_override
        else _selection_value(setup_selection, backend_env_var)
    )
    selected_renderer_map = renderer_map_override or _selection_value(setup_selection, map_env_var)

    if selected_backend_bin is None and auto_acquire:
        acquire_output_root = repo_root / "third_party" / "runtime_backends" / backend
        acquire_summary = build_renderer_backend_package_acquire(
            backend=backend,
            repo_root=repo_root,
            setup_summary_path=resolved_setup_summary_path,
            download_url=download_url,
            download_name=download_name,
            download_dir=download_dir,
            output_root=acquire_output_root,
            dry_run=dry_run,
            overwrite_download=overwrite_download,
        )
        issues.extend(str(item) for item in acquire_summary.get("issues", []) if str(item).strip())
        stage_summary = acquire_summary.get("stage")
        if isinstance(stage_summary, dict):
            stage_selection = stage_summary.get("selection", {})
            if isinstance(stage_selection, dict):
                if selected_backend_bin is None:
                    selected_backend_bin = _selection_value(stage_selection, backend_env_var)
                if selected_renderer_map is None:
                    selected_renderer_map = _selection_value(stage_selection, map_env_var)
        if acquire_summary.get("readiness", {}).get("stage_ready") and not dry_run:
            (
                refreshed_setup_summary,
                refreshed_setup_summary_path,
                refreshed_setup_env_path,
            ) = _refresh_setup_summary(
                repo_root=repo_root,
                workflow_root=workflow_root,
                prior_summary=setup_summary,
            )
            refreshed_selection = refreshed_setup_summary.get("selection", {})
            if isinstance(refreshed_selection, dict):
                selected_backend_bin = _selection_value(refreshed_selection, backend_env_var) or selected_backend_bin
                if selected_renderer_map is None:
                    selected_renderer_map = _selection_value(refreshed_selection, map_env_var)

    active_setup_summary = refreshed_setup_summary or setup_summary
    active_setup_summary_path = refreshed_setup_summary_path or resolved_setup_summary_path
    active_setup_selection = dict(active_setup_summary.get("selection", {}))
    active_setup_readiness = active_setup_summary.get("readiness", {})

    smoke_config_path, smoke_config_source = _determine_smoke_config(
        backend=backend,
        repo_root=repo_root,
        explicit_config=config_path,
        selection=active_setup_selection,
    )
    backend_compatibility = (
        _inspect_executable_host_compatibility(_resolve_path(selected_backend_bin))
        if selected_backend_bin is not None
        else {
            "host_compatible": False,
            "host_compatibility_reason": "backend runtime binary is not resolved",
            "binary_format": "missing",
            "file_description": "",
        }
    )
    backend_host_compatible = bool(backend_compatibility.get("host_compatible"))
    backend_host_compatibility_reason = str(
        backend_compatibility.get("host_compatibility_reason") or ""
    ).strip() or None
    helios_ready = bool(
        active_setup_readiness.get("helios_ready")
        or _selection_value(active_setup_selection, "HELIOS_BIN")
        or (
            _selection_value(active_setup_selection, "HELIOS_DOCKER_IMAGE")
            and _selection_value(active_setup_selection, "HELIOS_DOCKER_BINARY")
        )
    )
    smoke_output_dir = workflow_root / "smoke_run"
    smoke_summary_path = smoke_output_dir / "renderer_backend_smoke_summary.json"
    smoke_markdown_path = smoke_output_dir / "renderer_backend_smoke_report.md"
    smoke_html_path = smoke_output_dir / "renderer_backend_smoke_report.html"
    workflow_smoke_config_path = workflow_root / "renderer_backend_workflow_smoke_config.json"
    workflow_rerun_smoke_script_path = workflow_root / "renderer_backend_workflow_rerun_smoke.sh"

    smoke_args: list[str] = [
        "--config",
        str(smoke_config_path),
        "--backend",
        backend,
        "--output-dir",
        str(smoke_output_dir),
        "--summary-path",
        str(smoke_summary_path),
        "--markdown-report-path",
        str(smoke_markdown_path),
        "--html-report-path",
        str(smoke_html_path),
    ]
    if selected_backend_bin is not None:
        smoke_args.extend(["--backend-bin", selected_backend_bin])
    if selected_renderer_map is not None:
        smoke_args.extend(["--renderer-map", selected_renderer_map])
    for raw in option_overrides:
        smoke_args.extend(["--set-option", raw])
    planned_smoke_config_ready = False
    planned_smoke_config_error: str | None = None
    planned_forced_options: dict[str, Any] = {}
    try:
        smoke_base_config = _load_json(smoke_config_path)
        planned_effective_config, planned_forced_options = _build_smoke_effective_config(
            base_config=smoke_base_config,
            backend=backend,
            output_dir_override=smoke_output_dir,
            backend_bin_override=selected_backend_bin,
            renderer_map_override=selected_renderer_map,
            option_overrides=option_overrides,
            repo_root=repo_root,
        )
        planned_smoke_config_ready = True
    except Exception as exc:
        planned_smoke_config_error = str(exc)
        issues.append(f"Planned smoke config could not be materialized: {exc}")
        planned_effective_config = {
            "error": str(exc),
            "config_path": str(smoke_config_path),
            "config_source": smoke_config_source,
        }

    smoke_executed = False
    smoke_exit_code: int | None = None
    smoke_summary: dict[str, Any] | None = None
    smoke_stdout = ""
    smoke_ready = helios_ready and selected_backend_bin is not None and backend_host_compatible
    if not helios_ready:
        issues.append("HELIOS runtime is not ready for backend smoke.")
    if selected_backend_bin is None:
        issues.append(f"{backend_env_var} is not resolved for backend smoke.")
    elif not backend_host_compatible:
        issues.append(
            backend_host_compatibility_reason
            or f"{backend_env_var} is resolved but not executable on the current host."
        )

    if smoke_ready and not dry_run:
        smoke_executed = True
        with contextlib.redirect_stdout(io.StringIO()) as stdout:
            smoke_exit_code = smoke_main(smoke_args)
            smoke_stdout = stdout.getvalue()
        if smoke_summary_path.exists():
            smoke_summary = _load_json(smoke_summary_path)
    elif dry_run and not smoke_ready:
        smoke_exit_code = 1

    if dry_run:
        status = "DRY_RUN_READY" if smoke_ready else "DRY_RUN_BLOCKED"
    elif smoke_executed and smoke_exit_code == 0:
        status = "SMOKE_SUCCEEDED"
    elif smoke_executed:
        status = "SMOKE_FAILED"
    elif selected_backend_bin is None and acquire_summary is not None and acquire_summary.get("readiness", {}).get("download_url_resolved"):
        status = "ACQUIRE_BLOCKED"
    else:
        status = "BLOCKED"

    summary_path = workflow_root / "renderer_backend_workflow_summary.json"
    env_path = workflow_root / "renderer_backend_workflow.env.sh"
    report_path = workflow_root / "renderer_backend_workflow_report.md"
    final_selection = dict(active_setup_selection)
    final_selection[backend_env_var] = selected_backend_bin
    if selected_renderer_map is not None:
        final_selection[map_env_var] = selected_renderer_map
    recommended_next_command = None
    if status in {"BLOCKED", "DRY_RUN_BLOCKED", "ACQUIRE_BLOCKED"}:
        recommended_next_command = (
            "python3 scripts/acquire_renderer_backend_package.py "
            f"--backend {backend} --setup-summary {active_setup_summary_path}"
        )
    elif status == "DRY_RUN_READY":
        recommended_next_command = "python3 scripts/run_renderer_backend_smoke.py " + " ".join(
            f"\"{arg}\"" if " " in arg else arg for arg in smoke_args
        )
    blockers = _build_blockers(
        backend=backend,
        setup_summary=setup_summary,
        helios_ready=helios_ready,
        backend_bin=selected_backend_bin,
        backend_host_compatible=backend_host_compatible,
        backend_host_compatibility_reason=backend_host_compatibility_reason,
        auto_acquire=auto_acquire,
        acquire_summary=acquire_summary,
        smoke_executed=smoke_executed,
        smoke_exit_code=smoke_exit_code,
        planned_smoke_config_ready=planned_smoke_config_ready,
        planned_smoke_config_error=planned_smoke_config_error,
        recommended_next_command=recommended_next_command,
    )
    linux_handoff = _build_linux_handoff(
        backend=backend,
        repo_root=repo_root,
        workflow_root=workflow_root,
        final_selection=final_selection,
        planned_effective_config=planned_effective_config,
        planned_smoke_config_ready=planned_smoke_config_ready,
        planned_smoke_config_error=planned_smoke_config_error,
        selected_backend_bin=selected_backend_bin,
        selected_renderer_map=selected_renderer_map,
        backend_host_compatible=backend_host_compatible,
        backend_host_compatibility_reason=backend_host_compatibility_reason,
        acquire_summary=acquire_summary,
    )
    if (
        status in {"BLOCKED", "DRY_RUN_BLOCKED", "ACQUIRE_BLOCKED"}
        and linux_handoff.get("ready")
        and selected_backend_bin is not None
        and not backend_host_compatible
    ):
        recommended_next_command = linux_handoff.get("script_command") or linux_handoff.get("runner_command")
        blockers = _build_blockers(
            backend=backend,
            setup_summary=setup_summary,
            helios_ready=helios_ready,
            backend_bin=selected_backend_bin,
            backend_host_compatible=backend_host_compatible,
            backend_host_compatibility_reason=backend_host_compatibility_reason,
            auto_acquire=auto_acquire,
            acquire_summary=acquire_summary,
            smoke_executed=smoke_executed,
            smoke_exit_code=smoke_exit_code,
            planned_smoke_config_ready=planned_smoke_config_ready,
            planned_smoke_config_error=planned_smoke_config_error,
            recommended_next_command=recommended_next_command,
        )
    return {
        "backend": backend,
        "status": status,
        "success": status in {"SMOKE_SUCCEEDED", "DRY_RUN_READY"},
        "dry_run": dry_run,
        "generated_setup": generated_setup,
        "issues": issues,
        "blockers": blockers,
        "final_selection": final_selection,
        "recommended_next_command": recommended_next_command,
        "setup": {
            "summary_path": str(resolved_setup_summary_path),
            "readiness": setup_readiness,
            "selection": setup_selection,
            "commands": setup_summary.get("commands"),
        },
        "refreshed_setup": (
            {
                "summary_path": str(refreshed_setup_summary_path),
                "env_path": str(refreshed_setup_env_path),
                "readiness": refreshed_setup_summary.get("readiness"),
                "selection": refreshed_setup_summary.get("selection"),
                "commands": refreshed_setup_summary.get("commands"),
            }
            if refreshed_setup_summary is not None
            else None
        ),
        "acquire": acquire_summary,
        "smoke": {
            "ready": smoke_ready,
            "executed": smoke_executed,
            "exit_code": smoke_exit_code,
            "config_path": str(smoke_config_path),
            "config_source": smoke_config_source,
            "output_dir": str(smoke_output_dir),
            "summary_path": str(smoke_summary_path),
            "planned_effective_config_path": str(workflow_smoke_config_path),
            "planned_effective_config_ready": planned_smoke_config_ready,
            "planned_effective_config_error": planned_smoke_config_error,
            "planned_effective_config": planned_effective_config,
            "planned_forced_options": planned_forced_options,
            "stdout": smoke_stdout,
            "backend_bin": selected_backend_bin,
            "backend_host_compatible": backend_host_compatible,
            "backend_host_compatibility_reason": backend_host_compatibility_reason,
            "backend_binary_format": backend_compatibility.get("binary_format"),
            "backend_binary_architectures": backend_compatibility.get("binary_architectures"),
            "backend_translation_required": backend_compatibility.get("translation_required"),
            "backend_file_description": backend_compatibility.get("file_description"),
            "renderer_map": selected_renderer_map,
            "args": smoke_args,
            "summary": smoke_summary,
        },
        "linux_handoff": {
            **linux_handoff,
            "env_text": _render_linux_handoff_env_file(linux_handoff),
            "script_text": _render_linux_handoff_script(linux_handoff),
        },
        "commands": {
            "smoke": "python3 scripts/run_renderer_backend_smoke.py " + " ".join(
                f"\"{arg}\"" if " " in arg else arg for arg in smoke_args
            ),
            "rerun_smoke": (
                "python3 scripts/run_renderer_backend_smoke.py "
                f"--config {shlex.quote(str(workflow_smoke_config_path))} "
                f"--backend {backend} "
                f"--output-dir {shlex.quote(str(smoke_output_dir))}"
            )
            if planned_smoke_config_ready
            else None,
            "acquire": (
                "python3 scripts/acquire_renderer_backend_package.py "
                f"--backend {backend} --setup-summary {active_setup_summary_path}"
            ),
            "linux_handoff": linux_handoff.get("script_command"),
        },
        "artifacts": {
            "summary_path": str(summary_path),
            "env_path": str(env_path),
            "report_path": str(report_path),
            "next_step_script_path": str(workflow_root / "renderer_backend_workflow_next_step.sh"),
            "smoke_config_path": str(workflow_smoke_config_path),
            "rerun_smoke_script_path": str(workflow_rerun_smoke_script_path),
            "linux_handoff_config_path": linux_handoff["artifacts"]["handoff_config_path"],
            "linux_handoff_env_path": linux_handoff["artifacts"]["handoff_env_path"],
            "linux_handoff_script_path": linux_handoff["artifacts"]["handoff_script_path"],
            "refreshed_setup_summary_path": (
                str(refreshed_setup_summary_path) if refreshed_setup_summary_path is not None else None
            ),
            "refreshed_setup_env_path": (
                str(refreshed_setup_env_path) if refreshed_setup_env_path is not None else None
            ),
        },
    }


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    repo_root = Path(__file__).resolve().parents[3]
    workflow_root = (
        _resolve_path(args.output_root)
        if args.output_root is not None
        else (repo_root / "artifacts" / "renderer_backend_workflow" / args.backend).resolve()
    )
    summary = build_renderer_backend_workflow(
        backend=args.backend,
        repo_root=repo_root,
        workflow_root=workflow_root,
        setup_summary_path=_resolve_path(args.setup_summary) if args.setup_summary is not None else None,
        config_path=_resolve_path(args.config) if args.config is not None else None,
        backend_bin_override=args.backend_bin,
        renderer_map_override=args.renderer_map,
        auto_acquire=args.auto_acquire,
        download_url=args.download_url,
        download_name=args.download_name,
        download_dir=_resolve_path(args.download_dir) if args.download_dir is not None else None,
        overwrite_download=args.overwrite_download,
        dry_run=args.dry_run,
        option_overrides=list(args.set_option),
    )
    summary_path = Path(summary["artifacts"]["summary_path"])
    env_path = Path(summary["artifacts"]["env_path"])
    report_path = Path(summary["artifacts"]["report_path"])
    next_step_script_path = Path(summary["artifacts"]["next_step_script_path"])
    workflow_smoke_config_path = Path(summary["artifacts"]["smoke_config_path"])
    workflow_rerun_smoke_script_path = Path(summary["artifacts"]["rerun_smoke_script_path"])
    linux_handoff_config_path = Path(summary["artifacts"]["linux_handoff_config_path"])
    linux_handoff_env_path = Path(summary["artifacts"]["linux_handoff_env_path"])
    linux_handoff_script_path = Path(summary["artifacts"]["linux_handoff_script_path"])
    _write_json(summary_path, summary)
    _write_json(workflow_smoke_config_path, summary["smoke"]["planned_effective_config"])
    _write_json(linux_handoff_config_path, summary["linux_handoff"]["config"])
    _write_text(env_path, _render_workflow_env_file(summary))
    _write_text(linux_handoff_env_path, summary["linux_handoff"]["env_text"])
    _write_text(report_path, _render_workflow_markdown_report(summary, summary_path))
    _write_executable_text(next_step_script_path, _render_next_step_script(summary))
    _write_executable_text(
        workflow_rerun_smoke_script_path,
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                "# Generated by renderer_backend_workflow.py",
                "",
                f"source {shlex.quote(str(env_path))}",
                summary["commands"]["rerun_smoke"]
                if summary["commands"]["rerun_smoke"]
                else "echo 'Workflow smoke config is not ready yet. Check renderer_backend_workflow_summary.json for blockers.'\nexit 1",
                "",
            ]
        ),
    )
    _write_executable_text(
        linux_handoff_script_path,
        summary["linux_handoff"]["script_text"],
    )
    print(json.dumps(summary, indent=2))
    return 0 if summary["success"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
